[package]
name = "cw721-updatable"
version = "1.0.3"
authors = [
    "Drew Taylor <drew.taylor@philabs.xyz>",
    "Ethan Frey <ethanfrey@users.noreply.github.com>",
    "Orkun Külçe <orkun@deuslabs.fi>",
]
edition = "2018"
description = "Definition and types for the CosmWasm-721 NFT interface, with updatable metadata"
license = "Apache-2.0"
repository = "https://github.com/archway-network/cw721-updatable"

[dependencies]
cw-utils = "0.13.4"
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8.10"
serde = { version = "1.0.140", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
